-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-03-24 11:49:21 SEČ
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

-- Přepneme se do správné databáze (PDB)
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Tímto zajistíme, že následující příkazy poběží pod uživatelem SANDRA
ALTER SESSION SET CURRENT_SCHEMA = SANDRA;

CREATE TABLE ACTIVITIES 
    ( 
     activity_ID INTEGER  NOT NULL , 
     date_time   DATE  NOT NULL , 
     type        VARCHAR2 (10 CHAR)  NOT NULL , 
     city_ID     INTEGER  NOT NULL 
    ) 
;

ALTER TABLE ACTIVITIES 
    ADD CONSTRAINT ACTIVITY_TYPE_CK 
    CHECK (type IN ('Match', 'Training')) 
;

ALTER TABLE ACTIVITIES 
    ADD CONSTRAINT ACTIVITY_PK PRIMARY KEY ( activity_ID ) ;

CREATE TABLE CITIES 
    ( 
     city_ID INTEGER  NOT NULL , 
     name    VARCHAR2 (50 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE CITIES 
    ADD CONSTRAINT CITY_PK PRIMARY KEY ( city_ID ) ;

ALTER TABLE CITIES 
    ADD CONSTRAINT CITY_name_UN UNIQUE ( name ) ;

CREATE TABLE INJURIES 
    ( 
     injury_ID        INTEGER  NOT NULL , 
     date_from        DATE  NOT NULL , 
     date_to          DATE , 
     reason           VARCHAR2 (255 CHAR)  NOT NULL , 
     PLAYER_member_ID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE INJURIES 
    ADD CONSTRAINT INJURY_PK PRIMARY KEY ( injury_ID ) ;

CREATE TABLE MATCHES 
    ( 
     activity_ID   INTEGER  NOT NULL , 
     opponent_name VARCHAR2 (155 CHAR)  NOT NULL , 
     pregame_time  INTEGER  NOT NULL 
    ) 
;

ALTER TABLE MATCHES 
    ADD CONSTRAINT MATCH_PK PRIMARY KEY ( activity_ID ) ;

CREATE TABLE PARENTS 
    ( 
     parent_ID    INTEGER  NOT NULL , 
     name         VARCHAR2 (20 CHAR)  NOT NULL , 
     last_name    VARCHAR2 (30 CHAR)  NOT NULL , 
     phone_number VARCHAR2 (20 CHAR)  NOT NULL , 
     email        VARCHAR2 (100 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE PARENTS 
    ADD CONSTRAINT PARENT_PK PRIMARY KEY ( parent_ID ) ;

ALTER TABLE PARENTS 
    ADD CONSTRAINT PARENT_email_UN UNIQUE ( email ) ;

ALTER TABLE PARENTS 
    ADD CONSTRAINT PARENT_phone_number_UN UNIQUE ( phone_number ) ;

CREATE TABLE PERFORMANCES 
    ( 
     performance_ID   INTEGER  NOT NULL , 
     status           VARCHAR2 (100 CHAR)  NOT NULL , 
     minutes_played   INTEGER  NOT NULL , 
     goals_scored     INTEGER  NOT NULL , 
     red_cards        INTEGER  NOT NULL , 
     yellow_cards     INTEGER  NOT NULL , 
     assists          INTEGER  NOT NULL , 
     evaluation       NUMBER (2,1) , 
     coach_note       VARCHAR2 (255 CHAR) , 
     activity_ID      INTEGER  NOT NULL , 
     PLAYER_member_ID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE PERFORMANCES 
    ADD CONSTRAINT PERFORMANCE_STATUS_CK 
    CHECK (status IN ('Excused', 'Present', 'Sick', 'Starting', 'Substitute', 'Unexcused')) 
;

ALTER TABLE PERFORMANCES 
    ADD CONSTRAINT PERFORMANCE_PK PRIMARY KEY ( PLAYER_member_ID, performance_ID ) ;

CREATE TABLE PHYSICAL_ATTRIBUTES 
    ( 
     physical_attribute_ID INTEGER  NOT NULL , 
     test_date             DATE  NOT NULL , 
     value                 INTEGER  NOT NULL , 
     PLAYER_member_ID      INTEGER , 
     physical_type_ID      INTEGER 
    ) 
;

ALTER TABLE PHYSICAL_ATTRIBUTES 
    ADD CONSTRAINT PHYS_ATTR_PK PRIMARY KEY ( physical_attribute_ID ) ;

CREATE TABLE PHYSICAL_TYPES 
    ( 
     physical_type_ID INTEGER  NOT NULL , 
     name             VARCHAR2 (255 CHAR)  NOT NULL , 
     unit             VARCHAR2 (20 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE PHYSICAL_TYPES 
    ADD CONSTRAINT PHYSICAL_TYPE_PK PRIMARY KEY ( physical_type_ID ) ;

ALTER TABLE PHYSICAL_TYPES 
    ADD CONSTRAINT PHYSICAL_TYPE_name_UN UNIQUE ( name ) ;

CREATE TABLE PLAYERS 
    ( 
     member_ID   INTEGER  NOT NULL , 
     facr_id     VARCHAR2 (10 CHAR)  NOT NULL , 
     weight      INTEGER  NOT NULL , 
     height      INTEGER  NOT NULL , 
     foot        VARCHAR2 (5 CHAR)  NOT NULL , 
     is_healthy  VARCHAR2 (5 CHAR)  NOT NULL , 
     position_ID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE PLAYERS 
    ADD 
    CHECK (foot IN ('Both', 'Left', 'Right')) 
;

ALTER TABLE PLAYERS 
    ADD CONSTRAINT PLAYER_IS_HEALTHY_CK 
    CHECK (is_healthy IN ('No', 'Yes')) 
;
CREATE UNIQUE INDEX PLAYER__IDX ON PLAYERS 
    ( 
     member_ID ASC 
    ) 
;

ALTER TABLE PLAYERS 
    ADD CONSTRAINT PLAYER_PK PRIMARY KEY ( member_ID ) ;

ALTER TABLE PLAYERS 
    ADD CONSTRAINT PLAYER_facr_id_UN UNIQUE ( facr_id ) ;

CREATE TABLE PLAYERS_PARENTS 
    ( 
     PLAYER_member_ID INTEGER  NOT NULL , 
     PARENT_parent_ID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE PLAYERS_PARENTS 
    ADD CONSTRAINT PLAYER_PARENTS_PK PRIMARY KEY ( PLAYER_member_ID, PARENT_parent_ID ) ;

CREATE TABLE POSITIONS 
    ( 
     position_ID INTEGER  NOT NULL , 
     name        VARCHAR2 (155 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE POSITIONS 
    ADD CONSTRAINT POSITION_PK PRIMARY KEY ( position_ID ) ;

ALTER TABLE POSITIONS 
    ADD CONSTRAINT POSITION_name_UN UNIQUE ( name ) ;

CREATE TABLE ROLES 
    ( 
     role_id INTEGER  NOT NULL , 
     name    VARCHAR2 (30 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE ROLES 
    ADD CONSTRAINT ROLE_PK PRIMARY KEY ( role_id ) ;

ALTER TABLE ROLES 
    ADD CONSTRAINT ROLE_role_id_UN UNIQUE ( role_id ) ;

CREATE TABLE TEAM_MEMBERS 
    ( 
     member_ID     INTEGER  NOT NULL , 
     username      VARCHAR2 (50 CHAR)  NOT NULL , 
     password_hash VARCHAR2 (255 CHAR)  NOT NULL , 
     name          VARCHAR2 (20 CHAR)  NOT NULL , 
     last_name     VARCHAR2 (30 CHAR)  NOT NULL , 
     date_of_birth DATE  NOT NULL , 
     phone_number  VARCHAR2 (20 CHAR)  NOT NULL , 
     email         VARCHAR2 (100 CHAR)  NOT NULL , 
     is_active     VARCHAR2 (5 CHAR)  NOT NULL , 
     role_id       INTEGER  NOT NULL , 
     city_ID       INTEGER  NOT NULL 
    ) 
;

ALTER TABLE TEAM_MEMBERS 
    ADD CONSTRAINT TEAM_MEMBER_IS_ACTIVE_CK 
    CHECK (is_active IN ('No', 'Yes')) 
;

ALTER TABLE TEAM_MEMBERS 
    ADD CONSTRAINT TEAM_MEMBER_PK PRIMARY KEY ( member_ID ) ;

ALTER TABLE TEAM_MEMBERS 
    ADD CONSTRAINT TEAM_MEMBER_email_UN UNIQUE ( email ) ;

ALTER TABLE TEAM_MEMBERS 
    ADD CONSTRAINT TEAM_MEMBER_phone_number_UN UNIQUE ( phone_number ) ;

ALTER TABLE TEAM_MEMBERS 
    ADD CONSTRAINT TEAM_MEMBER_username_UN UNIQUE ( username ) ;

CREATE TABLE TRAINING_GROUNDS 
    ( 
     ground_ID INTEGER  NOT NULL , 
     name      VARCHAR2 (255 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE TRAINING_GROUNDS 
    ADD CONSTRAINT TRAINING_GROUND_PK PRIMARY KEY ( ground_ID ) ;

ALTER TABLE TRAINING_GROUNDS 
    ADD CONSTRAINT TR_GROUND_name_UN UNIQUE ( name ) ;

CREATE TABLE TRAININGS 
    ( 
     activity_ID INTEGER  NOT NULL , 
     focus       VARCHAR2 (255 CHAR)  NOT NULL , 
     ground_ID   INTEGER  NOT NULL 
    ) 
;

ALTER TABLE TRAININGS 
    ADD CONSTRAINT TRAINING_PK PRIMARY KEY ( activity_ID ) ;

ALTER TABLE ACTIVITIES 
    ADD CONSTRAINT ACTIVITY_CITY_FK FOREIGN KEY 
    ( 
     city_ID
    ) 
    REFERENCES CITIES 
    ( 
     city_ID
    ) 
;

ALTER TABLE INJURIES 
    ADD CONSTRAINT INJURY_PLAYER_FK FOREIGN KEY 
    ( 
     PLAYER_member_ID
    ) 
    REFERENCES PLAYERS 
    ( 
     member_ID
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE MATCHES 
    ADD CONSTRAINT MATCH_ACTIVITY_FK FOREIGN KEY 
    ( 
     activity_ID
    ) 
    REFERENCES ACTIVITIES 
    ( 
     activity_ID
    ) 
;

ALTER TABLE PERFORMANCES 
    ADD CONSTRAINT PERF_ACTIVITY_FK FOREIGN KEY 
    ( 
     activity_ID
    ) 
    REFERENCES ACTIVITIES 
    ( 
     activity_ID
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE PERFORMANCES 
    ADD CONSTRAINT PERF_PLAYER_FK FOREIGN KEY 
    ( 
     PLAYER_member_ID
    ) 
    REFERENCES PLAYERS 
    ( 
     member_ID
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE PHYSICAL_ATTRIBUTES 
    ADD CONSTRAINT PHYS_ATTR_PHYS_TYPE_FK FOREIGN KEY 
    ( 
     physical_type_ID
    ) 
    REFERENCES PHYSICAL_TYPES 
    ( 
     physical_type_ID
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE PHYSICAL_ATTRIBUTES 
    ADD CONSTRAINT PHYS_ATTR_PLAYER_FK FOREIGN KEY 
    ( 
     PLAYER_member_ID
    ) 
    REFERENCES PLAYERS 
    ( 
     member_ID
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE PLAYERS 
    ADD CONSTRAINT PLAYER_POSITION_FK FOREIGN KEY 
    ( 
     position_ID
    ) 
    REFERENCES POSITIONS 
    ( 
     position_ID
    ) 
;

ALTER TABLE PLAYERS 
    ADD CONSTRAINT PLAYER_TEAM_MEMBER_FK FOREIGN KEY 
    ( 
     member_ID
    ) 
    REFERENCES TEAM_MEMBERS 
    ( 
     member_ID
    ) 
;

ALTER TABLE PLAYERS_PARENTS 
    ADD CONSTRAINT PLAYERS_PARENTS_PARENT_FK FOREIGN KEY 
    ( 
     PARENT_parent_ID
    ) 
    REFERENCES PARENTS 
    ( 
     parent_ID
    ) 
;

ALTER TABLE PLAYERS_PARENTS 
    ADD CONSTRAINT PLAYERS_PARENTS_PLAYER_FK FOREIGN KEY 
    ( 
     PLAYER_member_ID
    ) 
    REFERENCES PLAYERS 
    ( 
     member_ID
    ) 
;

ALTER TABLE TEAM_MEMBERS 
    ADD CONSTRAINT TEAM_MEMBER_CITY_FK FOREIGN KEY 
    ( 
     city_ID
    ) 
    REFERENCES CITIES 
    ( 
     city_ID
    ) 
;

ALTER TABLE TEAM_MEMBERS 
    ADD CONSTRAINT TEAM_MEMBER_ROLE_FK FOREIGN KEY 
    ( 
     role_id
    ) 
    REFERENCES ROLES 
    ( 
     role_id
    ) 
;

ALTER TABLE TRAININGS 
    ADD CONSTRAINT TRAINING_ACTIVITY_FK FOREIGN KEY 
    ( 
     activity_ID
    ) 
    REFERENCES ACTIVITIES 
    ( 
     activity_ID
    ) 
;

ALTER TABLE TRAININGS 
    ADD CONSTRAINT TRAINING_TR_GROUND_FK FOREIGN KEY 
    ( 
     ground_ID
    ) 
    REFERENCES TRAINING_GROUNDS 
    ( 
     ground_ID
    ) 
;

CREATE OR REPLACE VIEW SANDRA.AVAILABLE_PLAYERS_VW ( activity_ID, activity_date, name, last_name, facr_id, position_ID ) AS
SELECT 
    a.activity_ID,
    a.date_time AS activity_date,
    m.name, 
    m.last_name, 
    p.facr_id,
    p.position_ID
FROM ACTIVITIES a
JOIN PLAYERS p ON 1=1
JOIN TEAM_MEMBERS m ON m.member_ID = p.member_ID
WHERE m.is_active = 'Yes'
  AND NOT EXISTS (
      SELECT 1
      FROM INJURIES i
      WHERE i.player_member_ID = p.member_ID
        AND a.date_time >= i.date_from
        AND a.date_time < NVL(i.date_to, DATE '9999-12-31') + 1
  ) 
;

CREATE OR REPLACE TRIGGER SANDRA.FKNTM_PLAYERS_PARENTS 
BEFORE UPDATE OF PLAYER_member_ID, PARENT_parent_ID 
ON PLAYERS_PARENTS 
BEGIN 
  raise_application_error(-20225,'Non Transferable FK constraint  on table PLAYERS_PARENTS is violated'); 
END; 
/

CREATE OR REPLACE TRIGGER SANDRA.ARC_FKArc_1_MATCHES 
BEFORE INSERT OR UPDATE OF activity_ID 
ON MATCHES 
FOR EACH ROW 
DECLARE 
    d VARCHAR2 (10 CHAR); 
BEGIN 
    SELECT A.type INTO d 
    FROM ACTIVITIES A 
    WHERE A.activity_ID = :new.activity_ID; 
    IF (d IS NULL OR d <> 'Match') THEN 
        raise_application_error(-20223,'FK MATCH_ACTIVITY_FK in Table MATCHES violates Arc constraint on Table ACTIVITIES - discriminator column type doesn''t have value ''Match'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/

CREATE OR REPLACE TRIGGER SANDRA.ARC_FKArc_1_TRAININGS 
BEFORE INSERT OR UPDATE OF activity_ID 
ON TRAININGS 
FOR EACH ROW 
DECLARE 
    d VARCHAR2 (10 CHAR); 
BEGIN 
    SELECT A.type INTO d 
    FROM ACTIVITIES A 
    WHERE A.activity_ID = :new.activity_ID; 
    IF (d IS NULL OR d <> 'Training') THEN 
        raise_application_error(-20223,'FK TRAINING_ACTIVITY_FK in Table TRAININGS violates Arc constraint on Table ACTIVITIES - discriminator column type doesn''t have value ''Training'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/

CREATE SEQUENCE SANDRA.ACTIVITIES_activity_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER SANDRA.ACTIVITIES_activity_ID_TRG 
BEFORE INSERT ON ACTIVITIES 
FOR EACH ROW 
BEGIN 
    :NEW.activity_ID := ACTIVITIES_activity_ID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE SANDRA.CITIES_city_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER SANDRA.CITIES_city_ID_TRG 
BEFORE INSERT ON CITIES 
FOR EACH ROW 
BEGIN 
    :NEW.city_ID := CITIES_city_ID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE SANDRA.INJURIES_injury_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER SANDRA.INJURIES_injury_ID_TRG 
BEFORE INSERT ON INJURIES 
FOR EACH ROW 
BEGIN 
    :NEW.injury_ID := INJURIES_injury_ID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE SANDRA.PARENTS_parent_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER SANDRA.PARENTS_parent_ID_TRG 
BEFORE INSERT ON PARENTS 
FOR EACH ROW 
BEGIN 
    :NEW.parent_ID := PARENTS_parent_ID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE SANDRA.PERFORMANCES_performance_ID 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER SANDRA.PERFORMANCES_performance_ID 
BEFORE INSERT ON PERFORMANCES 
FOR EACH ROW 
BEGIN 
    :NEW.performance_ID := PERFORMANCES_performance_ID.NEXTVAL; 
END;
/

CREATE SEQUENCE SANDRA.PHYSICAL_ATTRIBUTES_physical_a 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER SANDRA.PHYSICAL_ATTRIBUTES_physical_a 
BEFORE INSERT ON PHYSICAL_ATTRIBUTES 
FOR EACH ROW 
BEGIN 
    :NEW.physical_attribute_ID := PHYSICAL_ATTRIBUTES_physical_a.NEXTVAL; 
END;
/

CREATE SEQUENCE SANDRA.PHYSICAL_TYPES_physical_type_I 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER SANDRA.PHYSICAL_TYPES_physical_type_I 
BEFORE INSERT ON PHYSICAL_TYPES 
FOR EACH ROW 
BEGIN 
    :NEW.physical_type_ID := PHYSICAL_TYPES_physical_type_I.NEXTVAL; 
END;
/

CREATE SEQUENCE SANDRA.POSITIONS_position_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER SANDRA.POSITIONS_position_ID_TRG 
BEFORE INSERT ON POSITIONS 
FOR EACH ROW 
BEGIN 
    :NEW.position_ID := POSITIONS_position_ID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE SANDRA.ROLES_role_id_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER SANDRA.ROLES_role_id_TRG 
BEFORE INSERT ON ROLES 
FOR EACH ROW 
BEGIN 
    :NEW.role_id := ROLES_role_id_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE SANDRA.TEAM_MEMBERS_member_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER SANDRA.TEAM_MEMBERS_member_ID_TRG 
BEFORE INSERT ON TEAM_MEMBERS 
FOR EACH ROW 
BEGIN 
    :NEW.member_ID := TEAM_MEMBERS_member_ID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE SANDRA.TRAINING_GROUNDS_ground_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER SANDRA.TRAINING_GROUNDS_ground_ID_TRG 
BEFORE INSERT ON TRAINING_GROUNDS 
FOR EACH ROW 
BEGIN 
    :NEW.ground_ID := TRAINING_GROUNDS_ground_ID_SEQ.NEXTVAL; 
END;
/

CREATE OR REPLACE TRIGGER SANDRA.trg_auto_excuse_injury
BEFORE INSERT ON PERFORMANCES
FOR EACH ROW
DECLARE
    v_activity_date   DATE;
    v_injury_reason   VARCHAR2(255); -- Proměnná pro uložení důvodu
BEGIN
    -- 1. Získání data aktivity
    BEGIN
        SELECT date_time 
        INTO v_activity_date
        FROM ACTIVITIES
        WHERE activity_ID = :NEW.activity_ID;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20001, 'Chyba: Aktivita ID ' || :NEW.activity_ID || ' neexistuje.');
    END;

    -- 2. Kontrola zranění a získání důvodu (reason) k datu aktivity
    BEGIN
        SELECT reason 
        INTO v_injury_reason
        FROM INJURIES
        WHERE player_member_ID = :NEW.player_member_ID
          AND v_activity_date >= date_from 
          AND v_activity_date < NVL(date_to, DATE '9999-12-31') + 1
          AND ROWNUM = 1; -- Pokud je víc záznamů, vezmeme první nalezený
          
        -- Pokud SELECT našel řádek, hráč je zraněný -> omluvíme ho
        :NEW.status := 'Excused';
        :NEW.coach_note := 'Auto-omluva: Zranění (' || v_injury_reason || ').';

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            -- Hráč není zraněný, neděláme nic
            NULL; 
    END;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             1
-- ALTER TABLE                             46
-- CREATE VIEW                              1
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          14
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         11
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
