spring.application.name=CoachApp

# Pripojeni k Oracle v OrbStacku
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=SANDRA
spring.datasource.password=heslo123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate nastaveni (JPA)
# validate = Spring jen zkontroluje, ze tabulky z init.sql v DB fakt jsou
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Nastaví odhlá?ení po 30 minutách ne?innosti
server.servlet.session.timeout= 30m